'use client';

import { useEffect, useRef, useState, type Ref } from 'react';
import { useFocusRing, useObjectRef } from 'react-aria';
import { IconButton } from '../../components/icon-button/IconButton';
import { cn } from '../../utils/cn';
import { codeBlockStyles } from './code-block-styles';

/** Material Symbols `content_copy`. */
const CopyIcon = () => (
  <svg viewBox="0 -960 960 960" fill="currentColor">
    <path d="M360-240q-33 0-56.5-23.5T280-320v-480q0-33 23.5-56.5T360-880h360q33 0 56.5 23.5T800-800v480q0 33-23.5 56.5T720-240H360Zm0-80h360v-480H360v480ZM200-80q-33 0-56.5-23.5T120-160v-560h80v560h440v80H200Z" />
  </svg>
);

/** Material Symbols `check`. */
const CheckIcon = () => (
  <svg viewBox="0 -960 960 960" fill="currentColor">
    <path d="M382-240 154-468l57-57 171 171 367-367 57 57-424 424Z" />
  </svg>
);

export interface CodeBlockClassNames {
  root?: string;
  header?: string;
  title?: string;
  pre?: string;
  code?: string;
  copyButton?: string;
}

export interface CodeBlockProps {
  /** Raw source — copied by the copy button and used as a fallback when `html` is absent. */
  code: string;
  /**
   * Build-time Shiki markup rendered inside `<pre><code>`. Trusted (build-generated); when
   * omitted, `code` renders as plain text.
   */
  html?: string;
  /** Language label, exposed on the root as `data-lang`. */
  lang?: string;
  /** Optional title shown in the header, e.g. a file name. It also names the code region. */
  title?: string;
  showLineNumbers?: boolean;
  /** @default true */
  copyable?: boolean;
  /** @default "Copy" */
  copyLabel?: string;
  /** @default "Copied" */
  copiedLabel?: string;
  className?: string;
  classNames?: CodeBlockClassNames;
  ref?: Ref<HTMLDivElement>;
}

const COPIED_RESET_MS = 2000;

/**
 * A documentation code block: build-time highlighted source with a copy button.
 *
 * Not an M3 component — it is a `vk` docs-support component (architecture decision #22).
 * `html` is trusted markup generated by the docs build (Shiki) and rendered inside
 * `<pre><code>`; its token colours resolve through `--shiki-*` custom properties bound to
 * the library's semantic colour roles, so the block follows every theme, mode and
 * contrast level. `code` is the raw source used by the copy button.
 *
 * @example
 * <CodeBlock code={source} html={highlighted} lang="tsx" title="Button.tsx" />
 */
export function CodeBlock({
  code,
  html,
  lang,
  title,
  showLineNumbers = false,
  copyable = true,
  copyLabel = 'Copy',
  copiedLabel = 'Copied',
  className,
  classNames,
  ref,
}: CodeBlockProps) {
  const rootRef = useObjectRef(ref);
  const [copied, setCopied] = useState(false);
  const timeout = useRef<ReturnType<typeof setTimeout>>(undefined);

  useEffect(() => () => clearTimeout(timeout.current), []);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      clearTimeout(timeout.current);
      timeout.current = setTimeout(() => setCopied(false), COPIED_RESET_MS);
    } catch (error) {
      if (process.env.NODE_ENV !== 'production') {
        console.warn('[@vkieu/mui] CodeBlock: clipboard copy failed', error);
      }
    }
  };

  // The source scrolls sideways, so it is a focusable, named region keyboard users can
  // scroll (WCAG 2.1.1; axe `scrollable-region-focusable`).
  const { focusProps, isFocusVisible } = useFocusRing();
  const styles = codeBlockStyles({ showLineNumbers });
  const showHeader = title != null || copyable;
  const regionLabel = title ?? (lang ? `${lang} code` : 'Code');

  return (
    <div
      ref={rootRef}
      data-copied={copied || undefined}
      data-lang={lang}
      className={styles.root({ class: cn(classNames?.root, className) })}
    >
      {showHeader && (
        <div className={styles.header({ class: classNames?.header })}>
          {title != null ? (
            <span className={styles.title({ class: classNames?.title })}>{title}</span>
          ) : (
            <span aria-hidden="true" />
          )}
          {copyable && (
            <IconButton
              variant="standard"
              size="sm"
              icon={copied ? <CheckIcon /> : <CopyIcon />}
              aria-label={copied ? copiedLabel : copyLabel}
              onPress={() => void copy()}
              className={classNames?.copyButton}
            />
          )}
        </div>
      )}
      {/* Code always reads left to right, also on RTL pages. */}
      <pre
        {...focusProps}
        tabIndex={0}
        role="region"
        aria-label={regionLabel}
        dir="ltr"
        data-focus-visible={isFocusVisible || undefined}
        className={styles.pre({ class: classNames?.pre })}
      >
        {html != null ? (
          <code
            className={styles.code({ class: classNames?.code })}
            dangerouslySetInnerHTML={{ __html: html }}
          />
        ) : (
          <code className={styles.code({ class: classNames?.code })}>{code}</code>
        )}
      </pre>
    </div>
  );
}
