import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';

const HEADER = '/* Generated by @vkieu/mui from src/tokens. Do not edit by hand. */\n\n';

export async function writeGenerated(path: string, css: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, `${HEADER}${css}\n`);
}
